title: Kyra Wulffert 
logo: "/images/nepal_trek-029.jpg?raw=true" 
description: > 
  <br>I am a data scientist and an IT solution architect with over a decade of experience working on client facing projects in international environments with local and remote teams.<br>
  <br>I am a Machine Learning enthusiast and a lifelong learner.<br>
  <br>I believe that technology can be used to focus human contribution where it is most needed.<br>
  <br> 
  <br>
  ## Conference Talks
  [Machine Learning for Continuous Integration](https://www.dropbox.com/sh/8pul23zevii3k25/AAD5ITWfOgLZPKagXiVW9jrga/avise%204%206.mov?dl=0), ODSC Europe 2019 – with Andrea Frittoli

  <a href="https://www.linkedin.com/in/kyrawulffert/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
